version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    #container_name: GitLab
    #restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        #external_url 'https://112.160.104.138:2443'
        external_url 'https://112.160.104.138:26789'
        #gitlab_rails['time_zone'] = 'America/Chicago'
        #gitlab_rails['gitlab_email_from'] = 'gitlab-no-reply@example.com'
        #gitlab_rails['gitlab_email_display_name'] = 'GitLab Administrator'
        #gitlab_rails['gitlab_email_reply_to'] = 'admin@hexample.com'
        gitlab_rails['backup_keep_time'] = 14515200
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "julyinsung@gmail.com"
        gitlab_rails['smtp_password'] = "eoqkrakstp2016"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 3
        logging['logrotate_frequency'] = "weekly"
        logging['logrotate_rotate'] = 52
        logging['logrotate_compress'] = "compress"
        logging['logrotate_method'] = "copytruncate"
        logging['logrotate_delaycompress'] = "delaycompress"
        #nginx['listen_port'] = 443
        #nginx['redirect_http_to_https'] = true
        #nginx['ssl_certificate'] = "/etc/ssl/certs/gitlab/server-cert.pem"
        #nginx['ssl_certificate_key'] = "/etc/ssl/certs/gitlab/server-key.pem"
        #nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        nginx['logrotate_frequency'] = "weekly"
        nginx['logrotate_rotate'] = 52
        nginx['logrotate_compress'] = "compress"
        nginx['logrotate_method'] = "copytruncate"
        nginx['logrotate_delaycompress'] = "delaycompress"
        # Add any other gitlab.rb configuration options if desired
    ports:
      - '26789:28080'
      #- '2443:443'
      - '222:22'
    volumes:
      - /WORK/gitlab/conf:/etc/gitlab
      - /WORK/gitlab/ssl:/etc/ssl/certs/gitlab
      - /WORK/gitlab/logs:/var/log/gitlab
      - /WORK/gitlab/main:/var/opt/gitlab

