version: '2'
services:
  redis:
    image: redis
#    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    ports:
      - '16379:6379'
    volumes:
      - /WORK/redis-data:/data
  
