version: '2'

services:
  redis:
    image: redis
    hostname: redis
    ports:
      - '16379:6379'
    command: --appendonly yes   
    volumes:
      - /WORK/redis-data:/data
    labels: 
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: broker-volume, broker-conf
      io.rancher.scheduler.affinity:host_label: ${host_label}
    
 # 외부 설정 파일 사용?
