name: Context Broker
description: |
  add text
version: v1
category: Applications
maintainer: Tomas Holcman <tomas.holcman@gmail.com>
labels:
  io.rancher.certified: Hubpop
labels:
  io.rancher.certified: Hubpop