.catalog:
  name: Gitlab Community
  version: 9.5.10-ce.0
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: gitlab-0

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 8085
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
