.catalog:
  name: "Context Broker"
  version: "v1.0"
  description: ""
  uuid: context-broker-1
  questions:  
    - variable: image
      label: "Image"
      type: "string"
      default: ""
      required: true  

cb:
  scale: 1