version: '2'

services:
  mysql:
    image: sameersbn/mysql:latest
    ports:
    - "49876:3306"
    environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
    volumes:
    - /WORK/data/redmine:/var/lib/mysql

  redmine:
    image: sameersbn/redmine:3.4.4-2
#    depends_on:
#    - mysql
    environment:
    - TZ=Asia/Korea

    - DB_ADAPTER=mysql2
    - DB_HOST=mysql
    - DB_PORT=49876
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production

#    - REDMINE_PORT=23456
    - REDMINE_HTTPS=false
    
    ports:
    - "45678:80"
    volumes:
    - /WORK/srv/redmine:/home/redmine/data
    - /WORK/logs/redmine:/var/log/redmine