version: '2'
services:
  redmine:
    image: redmine
    ports:
    - '23456:3000'
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
    - REDMINE_DB_MYSQL=dbredmine
    - REDMINE_DB_USERNAME=redmine
    - REDMINE_DB_PASSWORD=redmine
    - REDMINE_DB_DATABASE=redmine
    volumes:
      - /WORK/srv/redmine:/home/redmine/data
      - /WORK/logs/redmine:/var/log/redmine
  dbredmine:
    image: mysql:5.7
    ports:
    - '29876:3306'
    volumes:
      - /WORK/db/redmine:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always
    environment:
    - MYSQL_ROOT_PASSWORD=redmine
    - MYSQL_DATABASE=redmine
    - MYSQL_USER=redmine
    - MYSQL_PASSWORD=redmine    
    